[package]
name = "mergson"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.12", features = ["derive"] }
env_logger = "0.9.1"
log = "0.4.17"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
